<a href="https://colab.research.google.com/github/SylviaMwai/GDSC-PROJECTS/blob/main/SUPERVISED_MACHINE_LEARNING_GDSC(LOGISTIC_REGRESSION).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**LOGISTIC REGRESSION(SUPERVISED MACHINE LEARNING PART 2)**

In [ ]:
#importing libraries packages and functions
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
#getting our data
x=np.arange(10).reshape(-1,1)
y=np.array([0,1,0,0,1,1,1,1,1,1])
print(x)
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 0 0 1 1 1 1 1 1]


In [ ]:
#creating and fitting model
model=LogisticRegression(solver="liblinear",C=10.0,random_state=0)
model.fit(x,y)


LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [ ]:
#evaluate the model
p_pred=model.predict_proba(x)
y_pred=model.predict(x)
score=model.score(x,y)
report=classification_report(y,y_pred)

In [ ]:
#looking at the intercept and coefficients
print("intercept:",model.intercept_)
print("coef:",model.coef_,end="\n\n")

intercept: [-1.51632619]
coef: [[0.703457]]



In [ ]:
print("y_actual:",y)
print("y_pred:",y_pred)

y_actual: [0 1 0 0 1 1 1 1 1 1]
y_pred: [0 0 0 1 1 1 1 1 1 1]


In [ ]:
#Printing confusion matrix
print('confusion matrix:',confusion_matrix(y,y_pred),sep="\n",end="\n\n")

confusion matrix:
[[2 1]
 [1 6]]

